# Generated by Django 4.1.5 on 2023-08-02 14:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fetch_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('track_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), null=True, size=None)),
            ],
        ),
    ]
